apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: hello-world-app-service
  description: Hello world app
  annotations:
    backstage.io/kubernetes-label-selector: hello-world-app
  tags:
    - java
spec:
  type: service
  lifecycle: production
  owner: opensource-practice@capgemini.com
  system: insurance-product1




