apiVersion:  backstage.io/v1alpha1
kind: Component
metadata:
  name: hello-world-app-service
  labels:
    backstage.io/kubernetes-id: hello-world-app-service
spec:
  type: service
  lifecycle: production
  owner: opensource-practice@capgemini.com
  system: kubernates-app
  replicas: 3
  selector:
    matchLabels:
      app: hello-world-app
  template:
    metadata:
      labels:
        app: hello-world-app
        backstage.io/kubernetes-id: hello-world-app
    spec:
      containers:
      - name: ubuntu
        image: ubuntu
        command: 
        - /bin/sh
        args:
        - -c
        - "tail -f /dev/null"