apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-app-service
  labels:
    backstage.io/kubernetes-id: hello-world-app-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-world-app
  template:
    metadata:
      labels:
        app: hello-world-app
        backstage.io/kubernetes-id: hello-world-app
    spec:
      containers:
      - name: ubuntu
        image: ubuntu
        command: 
        - /bin/sh
        args:
        - -c
        - "tail -f /dev/null"